version: "3"
services:
  wv-server:
    build: 
      context: ./wv-server
      dockerfile: Dockerfile-prod
    ports:
      - 5000:5000
    volumes:
      - ./wv-server/app/data/:/app/data/:rw
  wv-client:
    build: 
      context: ./wv-client
      dockerfile: Dockerfile-prod
    ports:
      - 80:80
