version: "3"
services:
  wv-nginx-dev:
    image: nginx:1.15.8
    volumes:
      - ./wv-client/choosy.dev.conf:/etc/nginx/conf.d/choosy.conf
    ports:
      - 80:80
    entrypoint:
      - nginx
      - -g
      - daemon off;
  wv-react-dev:
    build: 
      context: ./wv-client
      dockerfile: Dockerfile-dev
    volumes:
      - ./wv-client/src:/usr/src/app/src:rw
    ports:
      - 3000:3000
  wv-flask-dev:
    build: 
      context: ./wv-server
      dockerfile: Dockerfile-dev
    volumes:
      - ./wv-server/app:/app:rw
    ports:
      - 5000:5000
