FROM python:3.7
COPY ./requirements.txt requirements.txt 
RUN pip install -r requirements.txt 
COPY ./app /app
EXPOSE 5000
WORKDIR /app
ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:5000", "--reload", "--worker-class", "gevent", "-w", "1", "--access-logfile", "-", "--log-level", "debug", "server:app"]
