export const ACTIONS = {  
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    LOGOUT: "LOGOUT",

    CREATE_CHOICE: "CREATE_CHOICE",
    READ_CHOICES: "READ_CHOICES",
    UPDATE_CHOICE: "UPDATE_CHOICE",
    UPDATE_USER: "UPDATE_USER",
    
    UPDATE_BRACKET: "UPDATE_BRACKET",
    UPDATE_RESULTS: "UPDATE_RESULTS",
    UPDATE_ROUND: "UPDATE_ROUND",

    CREATE_VOTE: "CREATE_VOTE",
    SET_VOTE: "SET_VOTE",
 
    CREATE_LIST: "CREATE_LIST",
    JOIN_LIST: "JOIN_LIST",
    LEAVE_LIST: "LEAVE_LIST",

    SHOW_LOADING: "SHOW_LOADING",
    SHOW_SUCCESS: "SHOW_SUCCESS",
    SHOW_ERROR: "SHOW_ERROR",
    SHOW_REJECT: "SHOW_REJECT",
    GOTO_PAGE: "GOTO_PAGE",
    GOTO_MODAL: "GOTO_MODAL",

    REQUEST_SUCCESS: "REQUEST_SUCCESS",
    REQUEST_REJECT: "REQUEST_REJECT",
    REQUEST_ERROR: "REQUEST_ERROR",

    NOACTION: "NOACTION"
}

export default ACTIONS
