export const ACTIONS = {
    // User Actions
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    LOGOUT: "LOGOUT",

    // Room actions
    JOIN: "JOIN",
    LEAVE: "LEAVE",
    UPDATE_SUGGESTIONS: "UPDATE_SUGGESTIONS",

    // Socket Actions
    SOCKET_ADD_USER: "SOCKET_ADD_USER",
    SOCKET_REMOVE_USER: "SOCKET_REMOVE_USER",

    SOCKET_ADD_CHOICE: "SOCKET_ADD_CHOICE",
    SOCKET_UPDATE_CHOICE: "SOCKET_UPDATE_CHOICE",

    SOCKET_ADD_VOTE: "SOCKET_VOTE",
    SOCKET_UPDATE_VOTE: "SOCKET_UPDATE_VOTE",

    // Nav Actions
    LOADING: "LOADING",
    NAVIGATE: "NAVIGATE",
    OPEN_MODAL: "OPEN_MODAL",

    CREATE_ROOM: "CREATE_ROOM",

    // Request Actions
    REQUEST_SUGGESTIONS: "REQUEST_SUGGESTIONS",
    REQUEST_RANDOM: "REQUEST_RANDOM",

}

export default ACTIONS
